# Generated by Django 2.2.5 on 2020-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
