# Generated by Django 2.2.5 on 2020-07-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
