# Generated by Django 2.2.5 on 2020-07-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_order_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beer',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product_product',
        ),
    ]
